apiVersion: istio.openshift.com/v1alpha1
kind: Installation
metadata:
  name: istio-installation
  namespace: istio-operator
spec:
  deployment_type: openshift
  istio:
    authentication: true # enable mTLS
    community: false
    prefix: registry.access.redhat.com/openshift-istio-tech-preview/
    version: 0.9.0
  jaeger:
    prefix: registry.access.redhat.com/distributed-tracing-tech-preview/
    version: 1.11.0
    elasticsearch_memory: 1Gi
  kiali:
    username: admin
    password: admin
    prefix: registry.access.redhat.com/openshift-istio-tech-preview/
    version: 0.15.0
#  launcher:
#    openshift:
#      user: developer
#      password: developer
#    github:
#      username: YOUR_GITHUB_USERNAME
#       # the token should have `public_repo`, `read:org`, and `admin:repo_hook` permissions
#      token: YOUR_GITHUB_TOKEN
