apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: thorntail-istio-tracing-greeting
  annotations:
    iconClass: icon-jboss
    tags: thorntail, distributed tracing, java, microservice
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    description: The Istio Distributed Tracing example shows distributed tracing with Jaeger on Istio
parameters:
- name: SOURCE_REPOSITORY_URL
  description: The source URL for the application
  displayName: Source URL
  value: https://github.com/thorntail-examples/istio-tracing.git
  required: true
- name: SOURCE_REPOSITORY_REF
  description: The branch name for the application
  displayName: Source Branch
  value: master
  required: true
- name: SOURCE_REPOSITORY_DIR
  description: The location within the source repo of the application
  displayName: Source Directory
  value: greeting-service
  required: true
- name: GITHUB_WEBHOOK_SECRET
  description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  required: true
  from: '[a-zA-Z0-9]{40}'
  generate: expression
- name: MAVEN_MIRROR_URL
  description: URL of a Maven repository that will be used during build phase as a global Maven mirror
  displayName: Maven Mirror URL
  required: false
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: thorntail-istio-tracing-greeting
  spec: {}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: runtime-thorntail-istio-tracing-greeting
  spec:
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: thorntail-istio-tracing-greeting
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: thorntail-istio-tracing-greeting:latest
    postCommit: {}
    resources: {}
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: runtime-thorntail-istio-tracing-greeting:latest
        incremental: true
        env:
        - name: MAVEN_ARGS_APPEND
          value: "-pl ${SOURCE_REPOSITORY_DIR}"
        - name: MAVEN_MIRROR_URL
          value: "${MAVEN_MIRROR_URL}"
        - name: ARTIFACT_DIR
          value: "${SOURCE_REPOSITORY_DIR}/target"
        - name: ARTIFACT_COPY_ARGS
          value: "*-thorntail.jar"
      type: Source
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: thorntail-istio-tracing-greeting
      group: io.thorntail.example
    name: thorntail-istio-tracing-greeting
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: thorntail-istio-tracing-greeting
      group: io.thorntail.example
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: "true"
        labels:
          app: thorntail-istio-tracing-greeting
          group: io.thorntail.example
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: thorntail-istio-tracing-greeting:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            # the usual `httpGet` probe won't work, because the Istio proxy in the sidecar container
            # will prevent the kubelet from reaching the health endpoint
            exec:
              command:
              - curl
              - http://localhost:8080/health
            initialDelaySeconds: 180
          name: thorntail
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            # the usual `httpGet` probe won't work, because the Istio proxy in the sidecar container
            # will prevent the kubelet from reaching the health endpoint
            exec:
              command:
              - curl
              - http://localhost:8080/health
            initialDelaySeconds: 10
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - thorntail
        from:
          kind: ImageStreamTag
          name: thorntail-istio-tracing-greeting:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: thorntail-istio-tracing-greeting
    labels:
      app: thorntail-istio-tracing-greeting
      group: io.thorntail.example
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: thorntail-istio-tracing-greeting
      group: io.thorntail.example
